/*
 * @Author: vblazing
 * @Date: 2025-09-02 18:01:24
 * @LastEditors: VBlazing
 * @LastEditTime: 2025-10-25 00:02:23
 * @Description: 布局
 */
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { notFound } from "next/navigation";
import { hasLocale, NextIntlClientProvider } from "next-intl";
import { setRequestLocale } from "next-intl/server";
import { ThemeProvider } from "next-themes";
import ErrorManagerClient from "@/components/common/error_manager_client";
import Header from "@/components/layout/header";
import Footer from "@/components/layout/footer";
import { Toaster } from "@/components/ui/sonner";
import { routing } from "@/lib/i18n/routing";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export function generateStaticParams() {
  return routing.locales.map((locale) => ({ locale }));
}

export default async function LocaleLayout({
  children,
  params,
}: LayoutProps<"/[locale]">) {
  const { locale } = await params;

  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  setRequestLocale(locale);

  return (
    <html lang={locale} suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* 国际化 */}
        <NextIntlClientProvider>
          {/* 主题 */}
          <ThemeProvider
            attribute="class"
            enableSystem={false}
            storageKey="VBLAZING_THEME"
          >
            <div className="bg-main-content flex min-h-screen w-full flex-col items-center font-sans sm:items-start">
              <Header />
              <main className="flex w-full flex-1 flex-col items-center sm:items-start">
                {children}
              </main>
              <Footer />
            </div>
            <Toaster position="top-right" />
            <ErrorManagerClient />
          </ThemeProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
